apiVersion: v1
kind: Namespace
metadata:
  name: api-tests
---
apiVersion: batch/v1
kind: Job
metadata:
  name: api-test-runner
  namespace: api-tests
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: test-runner
        image: python:3.9-slim
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args:
        - -c
        - |
          pip install requests azure-servicebus
          cd /tests
          # Create a writable directory for results
          mkdir -p /tmp/results
          # Set environment variable for writable location
          export RESULTS_DIR=/tmp/results
          python api_tests.py
        env:
        - name: SERVICE_BUS_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-secrets
              key: service-bus-connection-string
        - name: TEST_ENVIRONMENT
          value: "kubernetes"
        - name: GITHUB_SHA
          value: "minikube-test"  # This will be replaced by sed
        - name: GITHUB_REF
          value: "refs/heads/main"  # This will be replaced by sed
        - name: RESULTS_DIR
          value: "/tmp/results"
        volumeMounts:
        - name: test-files
          mountPath: /tests
        - name: config-volume
          mountPath: /config
      volumes:
      - name: test-files
        configMap:
          name: test-files
      - name: config-volume
        configMap:
          name: test-config